### ISSUE TITLE
Api source?

### ISSUE THREAD

**Issue by animemandir** [shyam2520/JAAW#4]
what is the api source code for ttps://jaaw-api.herokuapp.com

**Comment by shyam2520** [comment]
> what is the api source code for ttps://jaaw-api.herokuapp.com

 just scrapes other popular websites 
Yeah but that's broken right now so yeah the sites down

**Comment by KshitijKalambe** [comment]
> 

make the repo public

**Comment by shyam2520** [comment]
The repo is getting deprecated

**Comment by shyam2520** [comment]
> > 
> 
> make the repo public

gogoanime i just use their apis
